# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb-guided-dive',
                'doc_host': 'https://vtecftwy.github.io',
                'git_url': 'https://github.com/vtecftwy/nb-guided-dive',
                'lib_path': 'nb_guided_dive'},
  'syms': {'nb_guided_dive.core': {'nb_guided_dive.core.foo': ('core.html#foo', 'nb_guided_dive/core.py')}}}