# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nb-guided-dive',
                'doc_host': 'https://vtecftwy.github.io',
                'git_url': 'https://github.com/vtecftwy/nb-guided-dive',
                'lib_path': 'nb_guided_dive'},
  'syms': { 'nb_guided_dive.core': {'nb_guided_dive.core.foo': ('core.html#foo', 'nb_guided_dive/core.py')},
            'nb_guided_dive.imports': { 'nb_guided_dive.imports.clean_image_directory': ( 'imports.html#clean_image_directory',
                                                                                          'nb_guided_dive/imports.py'),
                                        'nb_guided_dive.imports.config_fastai_for_colab': ( 'imports.html#config_fastai_for_colab',
                                                                                            'nb_guided_dive/imports.py'),
                                        'nb_guided_dive.imports.gv': ('imports.html#gv', 'nb_guided_dive/imports.py'),
                                        'nb_guided_dive.imports.mount_gdrive': ('imports.html#mount_gdrive', 'nb_guided_dive/imports.py')}}}