"""Functions and classes used across the package"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/00_core.ipynb.

# %% auto #0
__all__ = ['imported_objects', 'mount_gdrive', 'config_fastai_for_dive', 'install_package', 'gv', 'ml_process']

# %% ../nbs-dev/00_core.ipynb #0db1c678
imported_objects  = ['np', 'pd','shutil', 'Path']
try:
    __all__.extend(imported_objects)
except:
    __all__ = imported_objects

# %% ../nbs-dev/00_core.ipynb #e5e042d7
from nbdev import showdoc
from pathlib import Path
from fastai.vision.all import set_seed

import numpy as np
import pandas as pd
import graphviz
import matplotlib as mpl
import os
import shutil
import subprocess
import sys
import torch
import warnings

# %% ../nbs-dev/00_core.ipynb #89e738fe
def mount_gdrive(path_to_ds=None):
    """Mounts Google Drive to the colab environment when run on Google Colab"""
    try:
        from google.colab import drive
        drive.mount('/content/gdrive')
        print(f"Google Drive mounted successfully.")
    except:
        print('Nobebook is ran locally. No need to mount Google Drive.')

# %% ../nbs-dev/00_core.ipynb #5e388b22
def config_fastai_for_dive():
    """Setup the nbs environment for the guided dive notebooks. This includes:

    - Ignoring warnings
    - Setting matplotlib settings
    - Setting fastai seed
    - Setting pytorch settings
    - Setting numpy and pandas settings
    - Mounting Google Drive (if on colab)
    """
    
    warnings.filterwarnings('ignore')
    
    # matplotlib settings
    mpl.rcParams['savefig.dpi']= 200
    mpl.rcParams['font.size']=12
    
    # fastai seed
    set_seed(88)
    
    # pytorch settings
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.set_printoptions(linewidth=200)

    # numpy and pandas settings
    np.set_printoptions(linewidth=200)
    pd.set_option('display.max_columns',999)
    
    # mount goggle gdrive
    mount_gdrive()

# %% ../nbs-dev/00_core.ipynb #13301d31
def install_package(
    package_name:str, # The name of the package to install.
    ):
    """Install a Python package using pip in the current Jupyter Notebook environment. """
    try:
        # Run the pip install command
        subprocess.check_call([sys.executable, "-m", "pip", "install", package_name])
        print(f"Package '{package_name}' installed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Failed to install package '{package_name}'. Error: {e}")

# %% ../nbs-dev/00_core.ipynb #ac129b5d
def gv(code=None): 
    """Create a Graphviz source object with the given code."""
    return graphviz.Source('digraph G{ rankdir="LR"' + code + '; }')

def ml_process():
    """Setuep a visual representation of the machine learning process using Graphviz."""
    code = '''ordering=in
        problem[shape=cds width=1 height=1 label="1\nFrame business problem \ninto a ML problem"]
        data[shape=cylinder width=1 height=1 label="2\nCollect, and prepare \ndata, incl. labeling"]
        modeling[shape=box3d width=1 height=1 label="3\nBuild model \nand train it"]
        evaluate[shape=component width=1 height=1 label="4\nEvaluate and \nvalidate model"]
        improve[shape=rarrow width=1 height=1 label="5\nImprove model to \nreach expected standard"]
        problem->data->modeling->evaluate->improve'''
    return gv(code)
