# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/02_diffusion.ipynb.

# %% auto 0
__all__ = ['imported_objects', 'mount_gdrive', 'config_hugginface_for_colab']

# %% ../nbs-dev/02_diffusion.ipynb 3
imported_objects  = [
    'Image', 'concat','torch', 'logging', 'Path', 'notebook_login', 'StableDiffusionPipeline', 'plt', 
    'StableDiffusionImg2ImgPipeline', 'FastDownload'
]
try:
    __all__.extend(imported_objects)
except:
    __all__ = imported_objects

# %% ../nbs-dev/02_diffusion.ipynb 4
from PIL import Image
from fastcore.all import concat
import torch, logging
from pathlib import Path
from huggingface_hub import notebook_login
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
from diffusers import StableDiffusionImg2ImgPipeline
from fastdownload import FastDownload

# %% ../nbs-dev/02_diffusion.ipynb 5
def mount_gdrive(path_to_ds=None):

    if path_to_ds is None:
        dataset = Path('/content/gdrive/MyDrive/img-ds.zip')
    else:
        dataset = Path(path_to_ds)

    try:
        from google.colab import drive
        drive.mount('/content/gdrive')
        if not dataset.is_file():
            raise ValueError(f"Dataset cannot be found at <{dataset.absolute()}> ")
    except:
        print('This notebook should be run on Google Colab')

# %% ../nbs-dev/02_diffusion.ipynb 6
def config_hugginface_for_colab():
    
    logging.disable(logging.WARNING)

    torch.manual_seed(1)
    if not (Path.home()/'.huggingface'/'token').exists(): notebook_login()
