"""Functions and classes to make notebooks for stable diffusion easier to handle"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/04_diffusion.ipynb.

# %% auto #0
__all__ = ['imported_objects']

# %% ../nbs-dev/04_diffusion.ipynb #c5879e28
imported_objects  = [
    'Image', 'concat','torch', 'logging', 'Path', 'notebook_login', 'StableDiffusionPipeline', 'plt', 
    'StableDiffusionImg2ImgPipeline', 'FastDownload'
]
try:
    __all__.extend(imported_objects)
except:
    __all__ = imported_objects

# %% ../nbs-dev/04_diffusion.ipynb #6f6e5bc9
from PIL import Image
from fastcore.all import concat
import torch, logging
from pathlib import Path
from huggingface_hub import notebook_login
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
from diffusers import StableDiffusionImg2ImgPipeline
from fastdownload import FastDownload
