"""Functions and classes to make notebooks for tabular data easier to use"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/02_tabular.ipynb.

# %% auto #0
__all__ = ['imported_objects']

# %% ../nbs-dev/02_tabular.ipynb #c5879e28
imported_objects  = ['np', 'pd','shutil', 'Path']
try:
    __all__.extend(imported_objects)
except:
    __all__ = imported_objects

# %% ../nbs-dev/02_tabular.ipynb #6f6e5bc9
import numpy as np
import pandas as pd
import matplotlib as mpl
import shutil
import torch
import warnings

from pathlib import Path
from PIL import Image

from pandas.api.types import CategoricalDtype
from scipy.cluster import hierarchy as hc

from .core import config_fastai_for_dive, ml_process
