"""Functions and classes to make notebooks for computer vision easier to handle"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/01_vision.ipynb.

# %% auto #0
__all__ = ['imported_objects', 'get_images', 'clean_image_directory', 'count_files', 'print_metrics']

# %% ../nbs-dev/01_vision.ipynb #c5879e28
imported_objects  = ['np', 'pd','shutil', 'Path', 'ddgs', 'display_image_cleaner']
try:
    __all__.extend(imported_objects)
except:
    __all__ = imported_objects

# %% ../nbs-dev/01_vision.ipynb #6f6e5bc9
import numpy as np
import pandas as pd
import graphviz
import matplotlib as mpl
import os
import shutil
import subprocess
import sys
import torch
import warnings

from ddgs import DDGS
from fastai.vision.all import set_seed
from fastai.vision.utils import download_images
from fastai.vision.widgets import ImagesCleaner , ImageClassifierCleaner
from jmd_imagescraper.imagecleaner import display_image_cleaner
from pathlib import Path
from PIL import Image
from .core import install_package, mount_gdrive, gv, ml_process, config_fastai_for_dive

from pandas.api.types import CategoricalDtype
from scipy.cluster import hierarchy as hc

# %% ../nbs-dev/01_vision.ipynb #61dae2e6
def get_images(keywords, label, path, max_results=100, page=1, download_images=True):
    """Retrieve images from duck duck go search results based on a list of keywords"""
    results = DDGS().images(
        query=keywords,
        region="wt-wt",
        safesearch="on",
        size=None,
        color="color",
        type_image='photo',
        layout=None,
        license_image=None,
        max_results=max_results,
        page=page
    )
    print(f"Searching for {max_results} images for {label}")
    if len(results) == 0:
        print(f"Not images found for {keywords}")
    else:
        urls = [r['image'] for r in results]
        if download_images:
            path2imgs = path / label
            print(f"Found {len(results)} images for label {label}. Downloading into {path2imgs.absolute()}")
            os.makedirs(path2imgs, exist_ok=True)
            download_images(path2imgs, urls=urls)
            print('All downloaded')
        else:
            for url in urls:
                print(url)

    return results

# %% ../nbs-dev/01_vision.ipynb #fb1f2c1d
def clean_image_directory(path, verbose=False):
    def check_img(img):
        try: _ = Image.open(img)
        except Exception as e:
            img = str(img).replace(" ","\ ")
            os.system(f"rm -f {img}");
            print(f"removing error img:{img}")

    for cls in path.iterdir():
        print(f"Checking images for class '{cls.name}':")
        for i, img in enumerate(cls.iterdir()):
            if verbose: print(i+1, end=' - ')
            check_img(img)
            if verbose: print('\n')

# %% ../nbs-dev/01_vision.ipynb #5b544ea9
def count_files(path):
    """Count the number if files in the folder pointed as path, and its subfolders"""
    if isinstance(path, str): path = Path(path)
    nb_img = len([f for f in path.iterdir() if f.is_file()])
    if nb_img > 0:
        print(f"{nb_img:,d} in folder {path.name}")
    for d in [d for d in path.iterdir() if d.is_dir()]:
        nb_img = len([f for f in d.iterdir() if f.is_file()])
        print(f"{nb_img:,d} in folder {d.name}")

# %% ../nbs-dev/01_vision.ipynb #d41e68b2
def print_metrics(cm, class_0='bad', class_1='good'):
    """Print FP, FN, Accuracy, Precision  and Recall"""
    nb_val_im = cm.sum()
    true_nb_im_per_class = cm.sum(axis=1)
    pred_nb_im_per_class = cm.sum(axis=0)

    print(f"Accurate predictions:               {cm[0,0] + cm[1,1]:3d} out of {nb_val_im:,d} validation images") 
    print(f"False Positive preds:               {cm[0,1]:3d} images classified as `{class_1}` but actually should be `{class_0}`)")   
    print(f"False Negative preds:               {cm[1,0]:3d} images classified as `{class_0}` but actually should be `{class_1}`)")
    print()
    print(f"Accuracy:                           {cm.diagonal().sum()/nb_val_im * 100:6.2f} %") 
    print(f"{'Precision for '+class_1+':':<33}   {cm[1, 1]/pred_nb_im_per_class[1] * 100:6.2f} %")   
    print(f"{'Recall for '+class_1+':':<33}   {cm[1,1]/true_nb_im_per_class[1] * 100:6.2f} %")
    
