"""Functions and classes to make notebooks for computer vision easier to handle"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/01_vision.ipynb.

# %% auto #0
__all__ = ['imported_objects', 'get_images', 'clean_image_directory', 'count_files', 'print_metrics']

# %% ../nbs-dev/01_vision.ipynb #c5879e28
imported_objects  = ['np', 'pd','shutil', 'Path', 'display_image_cleaner']
try:
    __all__.extend(imported_objects)
except:
    __all__ = imported_objects

# %% ../nbs-dev/01_vision.ipynb #6f6e5bc9
import numpy as np
import pandas as pd
import graphviz
import matplotlib as mpl
import os
import shutil
import subprocess
import sys
import torch
import warnings
import time

from ddgs import DDGS
from ddgs.exceptions import DDGSException, TimeoutException, RatelimitException
from fastai.vision.all import set_seed
from fastai.vision.utils import download_images
from fastai.vision.widgets import ImagesCleaner , ImageClassifierCleaner
from jmd_imagescraper.imagecleaner import display_image_cleaner
from pathlib import Path
from PIL import Image
from .core import install_package, mount_gdrive, gv, ml_process, config_fastai_for_dive

from pandas.api.types import CategoricalDtype
from scipy.cluster import hierarchy as hc

# %% ../nbs-dev/01_vision.ipynb #1e64c3df
def get_images(keywords, label, path, max_results=100, max_pages=15, skip_download=False):
    """Retrieve images search results based on a list of keywords"""
    def _ddgs_call():
        return DDGS().images(
            query=keywords,
            region="wt-wt",
            safesearch="on",
            size=None,
            color="color",
            type_image='photo',
            layout=None,
            license_image=None,
            max_results=max_results,
            page=page,
        )
    
    nb_imgs, page = 0, 1
    while nb_imgs < max_results and page < max_pages:
        print(f"Searching for {max_results} images for {label} (page {page}). {nb_imgs} images found so far...")
        try:
            results = _ddgs_call()
        except TimeoutException as e:
            print("Timeout, retrying once...")
            results = _ddgs_call()            
        except RatelimitException as e:
            print("Rate limited, sleeping 20 sec before retry...")
            time.sleep(20)
            results = _ddgs_call()
        except DDGSException as e:
            print(f"Other DDGS error, retrying once... Error message: {e}")
            results = _ddgs_call()

        if len(results) == 0:
            if page == 1:
                print(f"Not images found for {keywords}")
            else:
                print(f"Only {nb_imgs} images found for {keywords} after {page} pages of search results")                  
            break
        else:
            path2imgs = path / label
            os.makedirs(path2imgs, exist_ok=True)
            urls = [r['image'] for r in results]
            if len(urls) > max_results - nb_imgs:
                # only pick the first urls to reach the number of images we want to download
                urls = urls[:max_results - nb_imgs]
            print(f"Found {len(urls)} images on search page {page}. Downloading into {path2imgs.absolute()}")
            if  skip_download:
                for url in urls:
                    print(url)
            else:
                download_images(path2imgs, urls=urls)
        nb_imgs += len(urls)
        page += 1
    print('All results downloaded')
    print(f"Found {nb_imgs} images for label {label}")

# %% ../nbs-dev/01_vision.ipynb #fb1f2c1d
def clean_image_directory(path, verbose=False):
    def check_img(img):
        try: _ = Image.open(img)
        except Exception as e:
            img = str(img).replace(" ","\ ")
            os.system(f"rm -f {img}");
            print(f"removing error img:{img}")

    for cls in path.iterdir():
        print(f"Checking images for class '{cls.name}':")
        for i, img in enumerate(cls.iterdir()):
            if verbose: print(i+1, end=' - ')
            check_img(img)
            if verbose: print('\n')

# %% ../nbs-dev/01_vision.ipynb #5b544ea9
def count_files(path):
    """Count the number if files in the folder pointed as path, and its subfolders"""
    if isinstance(path, str): path = Path(path)
    nb_img = len([f for f in path.iterdir() if f.is_file()])
    if nb_img > 0:
        print(f"{nb_img:,d} in folder {path.name}")
    counts = {}
    for d in [d for d in path.iterdir() if d.is_dir()]:
        nb_img = len([f for f in d.iterdir() if f.is_file()])
        print(f"{nb_img:,d} in folder {d.name}")
        counts[d.name] = nb_img
    return counts

# %% ../nbs-dev/01_vision.ipynb #d41e68b2
def print_metrics(cm, class_0='bad', class_1='good'):
    """Print FP, FN, Accuracy, Precision  and Recall"""
    nb_val_im = cm.sum()
    true_nb_im_per_class = cm.sum(axis=1)
    pred_nb_im_per_class = cm.sum(axis=0)

    print(f"Accurate predictions:               {cm[0,0] + cm[1,1]:3d} out of {nb_val_im:,d} validation images") 
    print(f"False Positive preds:               {cm[0,1]:3d} images classified as `{class_1}` but actually should be `{class_0}`)")   
    print(f"False Negative preds:               {cm[1,0]:3d} images classified as `{class_0}` but actually should be `{class_1}`)")
    print()
    print(f"Accuracy:                           {cm.diagonal().sum()/nb_val_im * 100:6.2f} %") 
    print(f"{'Precision for '+class_1+':':<33}   {cm[1, 1]/pred_nb_im_per_class[1] * 100:6.2f} %")   
    print(f"{'Recall for '+class_1+':':<33}   {cm[1,1]/true_nb_im_per_class[1] * 100:6.2f} %")
    
